### ISSUE TITLE
请教下 your_user 指代的是 user对象还是什么？

### ISSUE THREAD

**Issue by zhigoo** [weidwonder/django-jwt-session-auth#2]
from django_jwt_session_auth import jwt_login
token = jwt_login(your_user, request, expire=your_expire_time_in_sec) # also you can set default expire time in settings

这个登陆的示例， you_user 指代的是什么意思？ 另外 这里返回的 token， 怎么放到header里面去给用户？

**Comment by weidwonder** [comment]
1. you_user 是指你自定义的用户或者django内置的User对象, 都可以
2. 我在这个代码下边有注释:
```
# then return this token to client. After that every time client requests, set HTTP header Authorization="JWT <token>"
```
就是说你需要吧token返还给客户端, 客户端自己加入头 Authorization="JWT <token>"
