### ISSUE TITLE
jwt_login与login_required的问题

### ISSUE THREAD

**Issue by lizhihuan** [weidwonder/django-jwt-session-auth#3]
说实话,网络上关于这个问题的信息不多,所以很认真地看了你的源码,现在给你的评价吧,有一些原理你是讲通了,但是代码没写对,没法用.比如说,jwt_login和login_requied根本就不对应,如何检查session?

**Comment by weidwonder** [comment]
login_requied是django用来检查它自己的User的, 这个你不能用的, 你想检查用户是否登录可以直接使用requests.jwt_user is not None即可, 如果你非要使用装饰器这种形式, 你可以编写一个@jwt_login_required, 后续可以提交一个pull request 我把你合并进来. 谢谢你提出的问题

**Comment by weidwonder** [comment]
我再说一下为什么不使用django自己的login_required校验吧，因为这里的用户是你自定义的用户类的实例，所以django的用户依然可以登录admin，如果复写request.user和login_required方法会导致admin不可用，所以不能这么做
