### ISSUE TITLE
奇怪,我只能获取到jwt user 不能获取到session

### ISSUE THREAD

**Issue by 23233** [weidwonder/django-jwt-session-auth#4]
![image](https://user-images.githubusercontent.com/12870070/35103425-c0b07c72-fca0-11e7-9220-73fe82ca89dc.png)

**Comment by weidwonder** [comment]
这是能获取到session但是是空字典, 请提供更多信息

**Comment by kennir** [comment]
我也是这个情况， 看代码里好像没有写过storage？
